server:
  port: 8888

spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/git/greetings/services/config/config-files
        git:
          uri: file://${user.home}/git/greetings
          basedir: services/config/config-files