eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      uri: http://localhost:8888

endpoints:
  sensitive: false

greetingsBaseUrl: /api/greeting

templatesBaseUrl: /api/template

pingBaseUrl: /api/ping
